Coding challenges
jkalandarov/js_exercises pull request #1
Opened 2024-12-20 19:16 UTC by CoderQudratov

2024-12-21 07:10 UTC, jkalandarov requested changes

2024-12-21 07:10 UTC, jkalandarov commented on src/exercise_1.js
> +// }
Please remove unnecessary comments

2024-12-21 07:10 UTC, jkalandarov commented on src/exercise_1.js
> +  console.log(err.message);
Please remove these code blocks since they don't have any effect on the implementation.

2024-12-21 07:44 UTC, CoderQudratov commented on src/exercise_1.js
> +  console.log(err.message);
Thanks for the tip, I changed the code as you said

2024-12-21 07:47 UTC, CoderQudratov commented on src/exercise_1.js
> +  console.log(err.message);
when results will be declared?

2024-12-21 07:49 UTC, jkalandarov commented on src/exercise_1.js
> +  console.log(err.message);
Soon :)

2024-12-24 14:49 UTC, jkalandarov reviewed
Thanks for answers

2024-12-24 14:49 UTC, closed without merging